[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
"""
body = """
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{% if version -%}
## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
## [Unreleased]
{% endif -%}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}

{% for commit in commits -%}
- {{ commit.message | split(pat="\n") | first | upper_first | trim }}\
  {% if commit.id %} ([{{ commit.id | truncate(length=7, end="") }}]({{ self::remote_url() }}/commit/{{ commit.id }})){% endif %}\
  {% if commit.remote.username %} by [@{{ commit.remote.username }}](https://github.com/{{ commit.remote.username | replace(from="[", to="%5B") | replace(from="]", to="%5D") }}){% endif %}\
  {% if commit.remote.pr_number %} in [#{{ commit.remote.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.remote.pr_number }}){% endif %}
{% endfor %}
{% endfor %}

{%- if github.contributors | filter(attribute="is_first_time", value=true) | length != 0 %}
## New Contributors

{% for contributor in github.contributors | filter(attribute="is_first_time", value=true) -%}
- [@{{ contributor.username }}](https://github.com/{{ contributor.username | replace(from="[", to="%5B") | replace(from="]", to="%5D") }}) made their first contribution\
  {% if contributor.pr_number %} in [#{{ contributor.pr_number }}]({{ self::remote_url() }}/pull/{{ contributor.pr_number }}){% endif %}
{% endfor %}
{% endif -%}
"""
footer = """
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{% for release in releases -%}
{% if release.version and release.previous.version -%}
[{{ release.version | trim_start_matches(pat="v") }}]: {{ self::remote_url() }}/compare/{{ release.previous.version }}..{{ release.version }}
{% elif release.previous.version -%}
[unreleased]: {{ self::remote_url() }}/compare/{{ release.previous.version }}..HEAD
{% endif -%}
{% endfor %}

<!-- generated by git-cliff -->
"""
trim = true

[git]
conventional_commits = false
filter_unconventional = false
commit_preprocessors = [{ pattern = '\((\w+\s)?#([0-9]+)\)', replace = "" }]
commit_parsers = [
  { message = '^(?i)(.*:\s*)?\b(add|support)', group = "Added" },
  { message = '^(?i)(.*:\s*)?\b(correct|fix)', group = "Fixed" },
  { message = '^(?i)(.*:\s*)?\b(delete|remove)', group = "Removed" },
  { message = '^.*', group = "Changed" },
]
filter_commits = false
topo_order = false
sort_commits = "newest"

[remote.github]
owner = "AndrejOrsula"
repo = "pymoveit2"
